repos:
-   repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.7  # Use latest tag on GitHub
    hooks:
    -   id: ripsecrets
        # uncomment to check additional patterns 
        # args:
        # - --additional-pattern 'mytoken*'
        # - --additional-pattern 'mykey*'
